### ISSUE TITLE
Collaborate on an official Netdisco docker image

### ISSUE THREAD

**Issue by ollyg** [irasnyd/netdisco#2]
Hi Ira,

@LBegnaud and I have been working on a docker image for Netdisco, and associated Docker Hub and Cloud accounts. We are pretty much there, now.

I see that you are also producing a high quality and popular image of Netdisco. I wonder whether we can collaborate and especially whether I can modify Netdisco itself to require less monkeypatching in the dockerfiles.

I note that we have used Debian whereas you have used CENTOS. I don't know whether this means we want to maintain two images going forward, or settle on one.

Please let me know what you think - and thank you very much for using Netdisco and helping others to use it as well!!

regards,
Oliver Gorwits.

**Comment by LBegnaud** [comment]
Wow this is beautiful. Not sure how I missed this when working on my implementation. There's a lot of good logic going on in this image.

**Comment by ollyg** [comment]
Hi @irasnyd - as we didn't have a response, I'm going to start borrowing some of your ideas for the official Netdisco docker image, and also updating Netdisco to better support docker (and require less monkeypatching from the dockerfile).

Thank you so much for your work on this - we really appreciate it! Commit bits to the Netdisco repos are freely available if you wish, and you can find us easily online to chat :-).

**Comment by irasnyd** [comment]
Hi!

I apologize for not noticing this issue earlier. I must have lost track of it during the holiday season.

Please feel free to take anything you would like from my code. It is already under a permissive license, but I am happy to re-license it to anything you would like. I'm also happy to review and test out the image that you end up with. It will be great to have an official Docker image for netdisco!
